apiVersion: v1
kind: Secret
metadata:
  name: kfp-storage-secret
type: Opaque
stringData:
  secret_key: "<secret key>"
  access_key: "<access key>"
  accessKeyID: "<access key id>"
  secretAccessKey: "<secret access key>"
